#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
#  install.sh — Dotfiles symlink installer
#  Creates symlinks from ~/.config/* → ~/dotfiles/*
#  Safe to re-run; existing symlinks are replaced, real directories are left.
# ─────────────────────────────────────────────────────────────────────────────

set -e

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$HOME/.config"

# ── Helpers ───────────────────────────────────────────────────────────────────

info()    { echo "  ✓ $1"; }
warn()    { echo "  ⚠  $1"; }
section() { echo; echo "▸ $1"; }

# ln_file <src> <dst>  — symlink a single file
ln_file() {
    local src="$1" dst="$2"
    mkdir -p "$(dirname "$dst")"
    ln -sf "$src" "$dst"
    info "$(basename "$dst")"
}

# ln_dir <src> <dst>  — symlink an entire directory
#   Removes dst first if it is a real directory (not already a symlink),
#   so we don't end up with a symlink nested inside the old directory.
ln_dir() {
    local src="$1" dst="$2"
    if [ -d "$dst" ] && [ ! -L "$dst" ]; then
        rm -rf "$dst"
    fi
    ln -sf "$src" "$dst"
    info "$(basename "$dst")/"
}

# ── Hyprland ──────────────────────────────────────────────────────────────────
section "Hyprland"
ln_file "$DOTFILES/hypr/hyprland.conf" "$CONFIG/hypr/hyprland.conf"

# ── Kitty ─────────────────────────────────────────────────────────────────────
section "Kitty"
ln_file "$DOTFILES/kitty/kitty.conf" "$CONFIG/kitty/kitty.conf"

# ── Fish ──────────────────────────────────────────────────────────────────────
section "Fish"
ln_file "$DOTFILES/fish/config.fish" "$CONFIG/fish/config.fish"

# ── Pywal templates ───────────────────────────────────────────────────────────
section "Pywal templates"
mkdir -p "$CONFIG/wal/templates"
for tpl in "$DOTFILES/wal/templates/"*; do
    cp "$tpl" "$CONFIG/wal/templates/$(basename "$tpl")"
    info "$(basename "$tpl")"
done

# ── Mako  (config generated by pywal) ────────────────────────────────────────
section "Mako"
mkdir -p "$CONFIG/mako"
if [ -f "$HOME/.cache/wal/mako" ]; then
    ln_file "$HOME/.cache/wal/mako" "$CONFIG/mako/config"
else
    warn "~/.cache/wal/mako not found yet — run 'sw <wallpaper>' to generate it"
fi

# ── SwayNotificationCenter ────────────────────────────────────────────────────
section "SwayNC"
ln_file "$DOTFILES/swaync/config.json" "$CONFIG/swaync/config.json"
ln_file "$DOTFILES/swaync/style.css"   "$CONFIG/swaync/style.css"

# ── Waybar ────────────────────────────────────────────────────────────────────
section "Waybar"
ln_dir "$DOTFILES/waybar" "$CONFIG/waybar"
chmod +x "$DOTFILES/waybar/get_language.sh"

# ── Rofi ──────────────────────────────────────────────────────────────────────
section "Rofi"
ln_dir "$DOTFILES/rofi" "$CONFIG/rofi"
chmod +x "$DOTFILES/rofi/generate-rofi.sh"

# ── Fastfetch ─────────────────────────────────────────────────────────────────
section "Fastfetch"
ln_file "$DOTFILES/fastfetch/config.jsonc" "$CONFIG/fastfetch/config.jsonc"
ln_file "$DOTFILES/fastfetch/cat.txt"      "$CONFIG/fastfetch/cat.txt"

# ── Screenshots directory ─────────────────────────────────────────────────────
section "Screenshots"
mkdir -p "$HOME/Pictures/Screenshots"
info "~/Pictures/Screenshots"

# ── Done ──────────────────────────────────────────────────────────────────────
echo
echo "────────────────────────────────────────────────────────────"
echo "  ✓ Dotfiles installed from: $DOTFILES"
echo
echo "  Run  sw <path/to/wallpaper>  to apply a pywal color scheme."
echo "  This regenerates the Rofi theme, reloads Waybar & SwayNC."
echo "────────────────────────────────────────────────────────────"
